In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("data/ForeignGifts_edu.csv")

df.head()

,ID,OPEID,Institution Name,City,State,Foreign Gift Received Date,Foreign Gift Amount,Gift Type,Country of Giftor,Giftor Name
0,1,102000,Jacksonville State University,Jacksonville,AL,43738,250000,Monetary Gift,CHINA,NaN
1,2,104700,Troy University,Troy,AL,43592,463657,Contract,CHINA,Confucius Institute Headquarters
2,3,105100,University of Alabama,Tuscaloosa,AL,43466,3649107,Contract,ENGLAND,Springer Nature Customer Service Ce
3,4,105100,University of Alabama,Tuscaloosa,AL,43472,1000,Contract,SAUDI ARABIA,Saudi Arabia Education Mission
4,5,105100,University of Alabama,Tuscaloosa,AL,43479,49476,Contract,SAUDI ARABIA,Saudi Arabia Education Mission

First, lets create a data frame 'uva' that only contains gifts to UVA

In [23]:
uva = df[df['Institution Name'] == 'University of Virginia']

uva.head()

,ID,OPEID,Institution Name,City,State,Foreign Gift Received Date,Foreign Gift Amount,Gift Type,Country of Giftor,Giftor Name
26235,26236,374500,University of Virginia,Charlottesville,VA,41822,3565,Monetary Gift,ENGLAND,West Yorkshire Police
26236,26237,374500,University of Virginia,Charlottesville,VA,41870,12265,Contract,ISRAEL,CureTech Ltd
26237,26238,374500,University of Virginia,Charlottesville,VA,41873,8187,Monetary Gift,ISRAEL,Branco Weiss Institute
26238,26239,374500,University of Virginia,Charlottesville,VA,41887,6437,Contract,ISRAEL,NovoCure Ltd
26239,26240,374500,University of Virginia,Charlottesville,VA,41904,216943,Contract,ISRAEL,InSightec-Image Guide Treatment Ltd

We can group by country and calculate the sums to show which countries are currently giving the most to UVA

In [26]:
country_uva_total_dons = uva.groupby('Country of Giftor')['Foreign Gift Amount'].sum().sort_values(ascending=False)

country_uva_total_dons

Country of Giftor
BANGLADESH         4228589
SWEDEN             4007552
TANZANIA           2776447
SWITZERLAND        2000000
ENGLAND            1950666
GUERNSEY           1500000
FINLAND            1008384
BERMUDA             900000
KOREA               862787
SINGAPORE           805000
THE NETHERLANDS     725670
ISRAEL              623655
RWANDA              284135
JAPAN               265970
FRANCE              250383
Name: Foreign Gift Amount, dtype: int64

Let's also see which countries are most frequently giving to UVA regardless of the sum of their gifts

In [27]:
country_uva_count_dons = uva.groupby('Country of Giftor')['Foreign Gift Amount'].count().sort_values(ascending=False)

country_uva_count_dons

Country of Giftor
ENGLAND            31
ISRAEL             12
BANGLADESH         10
SWEDEN             10
FINLAND             7
KOREA               6
FRANCE              5
THE NETHERLANDS     4
GUERNSEY            3
TANZANIA            3
SINGAPORE           2
SWITZERLAND         2
BERMUDA             1
JAPAN               1
RWANDA              1
Name: Foreign Gift Amount, dtype: int64

Lets repeat the same processes above for VCU, a big public school that is in our same state

In [43]:
vcu = df[df['Institution Name'] == 'Virginia Commonwealth University']

country_vcu_total_dons = vcu.groupby('Country of Giftor')['Foreign Gift Amount'].sum().sort_values(ascending=False)

country_vcu_count_dons = vcu.groupby('Country of Giftor')['Foreign Gift Amount'].count().sort_values(ascending=False)

country_vcu_total_dons.head(10)

Country of Giftor
QATAR              78867097
ENGLAND             2496691
GERMANY             2177743
SWITZERLAND         1390035
THE NETHERLANDS     1033947
SPAIN                675859
JAPAN                593294
AUSTRALIA            371196
CANADA               362866
ISRAEL               243898
Name: Foreign Gift Amount, dtype: int64

In [44]:
country_vcu_count_dons.head(10)

Country of Giftor
ENGLAND        23
CANADA         15
SWITZERLAND    11
QATAR          10
GERMANY        10
ISRAEL          7
JAPAN           6
BERMUDA         3
CHINA           3
SWEDEN          3
Name: Foreign Gift Amount, dtype: int64

We'll also do the same for our in-state rival Virginia Tech

In [46]:
vt = df[df['Institution Name'] == 'Virginia Polytechnic Institute & State University']

country_vt_total_dons = vt.groupby('Country of Giftor')['Foreign Gift Amount'].sum().sort_values(ascending=False)

country_vt_count_dons = vt.groupby('Country of Giftor')['Foreign Gift Amount'].count().sort_values(ascending=False)

country_vt_total_dons.head(10)

Country of Giftor
ENGLAND                 2586931
SPAIN                   1768507
OMAN                    1099939
CHINA                    976992
THE NETHERLANDS          850000
INDIA                    662899
UNITED ARAB EMIRATES     650000
CANADA                   590073
JAPAN                    547788
GERMANY                  533809
Name: Foreign Gift Amount, dtype: int64

In [48]:
country_vt_count_dons.head(10)

Country of Giftor
CHINA                   3
ENGLAND                 3
CANADA                  2
JAPAN                   2
OMAN                    2
SPAIN                   2
THE NETHERLANDS         2
UNITED ARAB EMIRATES    2
FINLAND                 1
FRANCE                  1
Name: Foreign Gift Amount, dtype: int64

And lastly, we'll do the same for UNC, a large public university often compared to UVA and only one state south

In [49]:
unc = df[df['Institution Name'] == 'University of North Carolina - Chapel Hill']

country_unc_total_dons = unc.groupby('Country of Giftor')['Foreign Gift Amount'].sum().sort_values(ascending=False)

country_unc_count_dons = unc.groupby('Country of Giftor')['Foreign Gift Amount'].count().sort_values(ascending=False)

country_unc_total_dons.head(10)

Country of Giftor
CANADA             14042140
SWITZERLAND         5371435
ZAMBIA              4347979
ENGLAND             2876760
FRANCE              2631412
SWEDEN              2476449
TAIWAN              2081694
DENMARK             1167893
MALAWI               976615
THE NETHERLANDS      782946
Name: Foreign Gift Amount, dtype: int64

In [50]:
country_unc_count_dons.head(10)

Country of Giftor
CANADA             118
ENGLAND             50
ZAMBIA              36
FRANCE              14
BELGIUM             13
DENMARK             12
TAIWAN               8
SWITZERLAND          7
THE NETHERLANDS      6
HONG KONG            3
Name: Foreign Gift Amount, dtype: int64